routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Route::get('/test', function () {
	$data =  App\Models\Cote::getFicheComplete(13);
	dd($data->get());																										
    return $data;
});

Route::get('/home', function(){
	if (auth()->check()) {
            $role = auth()->user()->users_roles;
            return redirect()->route($role.'.index');
        }
        
      return abort();
});

Route::get('/titulaires-login', 'Auth\TitulairesLoginController@showLoginForm')->name('prof-login');
Route::post('/titulaires-login', ['as'=> 'titulaires-login','uses'=>'Auth\TitulairesLoginController@login']);

/*|||||||||||||||||||||||||||||||||||||
|
|  Routes pour le professeur
|
|||||||||||||||||||||||||||||||||||||*/
Route::prefix('professeur')->group(function(){
	Route::name('professeur.')->group(function () {
		Route::get('/', 'Profs\DashboardController@index' )->name('index');
		Route::post('/redirect_fiche', 'Profs\DashboardController@redirectFiche' )->name('redirect_fiche');
		Route::get('/get_fiche/cours/{idcours}/{idtype_cotes}','Profs\DashboardController@getFiche')->name('get_fiche');
		Route::post('/set_cote','Profs\DashboardController@setCote')->name('set_cote');
		// Route::post('/send_fiche','Profs\DashboardController@sendFiche')->name('send_fiche');
		Route::get('/send_fiche/{type_cotes}/{cours}','Profs\DashboardController@sendFiche')->name('send_fiche');




		// Déconnexion prof
		Route::post('/prof-logout',function(){
			auth()->logout();
			return redirect()->route('prof-login');
		})->name('logout');
	});





	
});

/*|||||||||||||||||||||||||||||||||||||
|
|  Routes pour la section
|
|||||||||||||||||||||||||||||||||||||*/
Route::prefix('section')->group(function(){
	Route::name('section.')->group(function () {
		Route::get('/', 'Section\DashboardController@getListAuditoires')->name('index');
		// Session Import
		
		Route::get('/importation_cotes', 'Section\DashboardController@importSession')->name('session_import');
		Route::get('/importation_cotes/{type_cote}', 'Section\DashboardController@getImportSession')->name('get_session_import');
		Route::get('/importation_cote/{type_cote}/{auditoire}', 'Section\DashboardController@getImportSession')->name('get_session_import_by_auditoire');
		Route::get('/importation_fiche_cote', 'Section\DashboardController@getFicheImport')->name('get_fiche');
		
		// Etudiants
		Route::get('/etudiants', 'Section\DashboardController@getListAuditoiresEtudiants')->name('get_etudiants');
		Route::get('/get_etudiants_auditoires/{auditoire}', 'Section\DashboardController@getListStudent')->name('get_etudiants_by_auditoire');
		Route::resource('/gestion_etudiant', 'Gestions\EtudiantController')->only(['store']);


		// Cours
		Route::get('/get_cours_auditoires', 'Section\DashboardController@getListAuditoires')->name('get_cours');
		Route::get('/getCoursAuditoire/{auditoire}', 'Section\DashboardController@getCoursByAuditoire')->name('getCoursByAuditoire');
		Route::resource('/gestion_cours', 'Gestions\CoursController')->only(['store']);
		
		// Professeurs
		Route::get('/professeurs', 'Section\DashboardController@getListProfeseurs')->name('get_prof');
		Route::resource('/gestion_prof', 'Gestions\ProfController')->only(['store']);


	});
});

/*|||||||||||||||||||||||||||||||||||||
|
|  Routes pour le jury
|
|||||||||||||||||||||||||||||||||||||*/
Route::prefix('jury')->group(function(){
	Route::name('jury.')->group(function () {
		Route::get('/', 'Jury\DashboardController@index')->name('index');
		// Importation cotes
		Route::get('/importation_cotes', 'Jury\DashboardController@importSession')->name('session_import');
		Route::get('/importation_cotes/{type_cote}', 'Jury\DashboardController@getImportSession')->name('get_session_import');
		Route::get('/importation_cote/{type_cote}/{auditoire}', 'Jury\DashboardController@getCoursImportByAuditoire')->name('get_session_import_by_auditoire');
		Route::get('/importation_fiche_cote/{fiches_envoye}', 'Jury\DashboardController@getFicheImport')->name('get_fiche');
		

	});
});

Auth::routes();

app/Models/Section.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Section extends Model
{
    protected $primaryKey = 'idsections';
    
}

app/Http/Controllers/Section/DashboardController.php
<?php

namespace App\Http\Controllers\Section;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\DataTables\Section\ListeAuditoiresDataTable;
use App\DataTables\Section\AuditoiresImportDataTable;
use App\DataTables\Section\ListeEtudiantByAuditoireDataTable;
use App\DataTables\Section\ListeCoursByAuditoireDataTable;
use App\DataTables\Section\ListeProfesseursDataTable;
use App\DataTables\Section\ImportSessionDataTable;
// use App\DataTables\Section\BilanDataTable;
use App\Models\Auditoire;
use App\Models\Etudiant;
use App\Models\Cour;
use App\Models\Type_cote;
use Flashy;
class DashboardController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
	/*
    * Affiche la liste des auditoires
    * @param $dataTables un dataTable 
    * @return la vue liste_auditoire
    */
    public function index(){
    	return redirect()->route('section.getBilan');
    }
    
    /*
    * Affiche la liste des types de cotes
    * annee,examen,recours .... 
    */

    public function importSession(){
        $data = Type_cote::get();
        return view('section.session_import',compact('data'));
    }

    /*
    * Affiche la liste des auditoires
    * avec la route de liste de cours recu 
    * @return la vue liste_auditoire
    */

    public function getImportSession(Type_cote $type_cote, AuditoiresImportDataTable $dataTables){
        return $dataTables->with(['type_cote'=>$type_cote->idtype_cotes])->render('section.liste_auditoire',compact('section'));
    }

    /*
    * Affiche la fiche du cours récu
    * 
    * @return la vue liste_auditoire
    */
    public function getFicheImport(Type_cote $type_cote, Auditoire $auditoire,Cour $cour, AuditoiresImportDataTable $dataTables){
        return '';
    }



    /*
    * Affiche la liste des auditoires
    * @param $dataTables un dataTable 
    * @return la vue liste_auditoire
    */
    public function getListAuditoires(ListeAuditoiresDataTable $dataTables){
        return $dataTables->with(['route'=>'getCoursByAuditoire'])->render('section.liste_auditoire',compact('section'));
    }
    /*
    * retourne la liste des cours d'un auditoire
    * @param $dataTables un dataTable 
    * @return la vue liste_auditoire
    */
    public function getCoursByAuditoire(ListeCoursByAuditoireDataTable $dataTables,Auditoire $auditoire){
        return $dataTables->with(['idauditoires'=>$auditoire->idauditoires])->render('section.cours_auditoire',compact('auditoire'));
    }

    /*
    * retourne la liste des auditoires avec la route pour afficher les étudiant
    * @param $dataTables un dataTable 
    * @return la vue liste_auditoire
    */
    public function getListAuditoiresEtudiants(ListeAuditoiresDataTable $dataTables){
         return $dataTables->with(['route'=>'get_etudiants_by_auditoire'])->render('section.liste_auditoire',compact('section'));
    }
        /*
        * Affiche la liste des etudiant
        * @param $dataTables un dataTable 
        * @return la vue listeEtudiants
        */
    public function getListStudent(Auditoire $auditoire, ListeEtudiantByAuditoireDataTable $dataTables){
    	return $dataTables->with(['idauditoires'=>$auditoire->idauditoires])->render('section.listeEtudiants',compact('auditoire'));
    }

     /*
    * Affiche la liste des professeurs
    * @param $dataTables un dataTable 
    * @return la vue listeEtudiants
    */

    public function getListProfeseurs(ListeProfesseursDataTable $dataTables){
        return $dataTables->render('section.listeProfesseurs');
    }






    
}

resources/views/section/bilan.blade.php
@extends('layouts.master')
@include('partials.includes.dataTables.dataTables')
@include('partials.includes.dataTables.buttons')
@section('content')
<div class="container">
	<div class="card bg-light mb-3">
	  <div class="card-body">
		{!!$dataTable->table() !!}
	  </div>
	</div>
</div>	
@stop
@push('scripts')
{!!$dataTable->scripts() !!}
@endpush

resources/views/section/cours_auditoire.blade.php
@extends('layouts.default')
@include('partials.includes.dataTables.dataTables')
@include('partials.includes.dataTables.buttons')
@section('content')
<div class="container"  >
	<div class="row">
        <div class="col-md-12">
         <h2 class="badge badge-pill badge-info">{{ $auditoire->lib }}</h2>   
        </div>
    </div>
    <br>

	<button type="button" class="addModal btn btn-primary" data-toggle="modal" data-target="#exampleModalLong">
	  <span class="fas fa-plus"> </span> Nouveau cours
	</button>
	<br><br>
     {{-- <hr /> --}}
	<div class="card bg-light mb-3">
	  <div class="card-body" >
		{!!$dataTable->table() !!}
	  </div>
	</div>
	@include('partials.includes.formulaires.ajoutCoursForm',['idauditoireSelected'=>$auditoire->idauditoires])



</div>	
@stop
@push('scripts')
{!!$dataTable->scripts() !!}

@endpush

resources/views/section/listeEtudiants.blade.php
@extends('layouts.default')
@include('partials.includes.dataTables.dataTables')
@include('partials.includes.dataTables.buttons')
@section('content')
<div class="container">
	<h3>{{ $auditoire->lib }}</h3>
	{{-- <a  href="{{ route('section.getListStudentEnroles',$auditoire->idauditoires) }}" type="button" class="btn btn-info">
  		<span class="fa fa-user"> </span> Etudiants enrôlés
	</a><br><br> --}}
	<div class="create">
		<button type="button" class="addModal btn btn-info" data-toggle="modal" data-target="#editModal">
	  		 <span class="fa fa-plus"> </span> Ajouter un étudiant
		</button>
	</div>
	<br>
	<div class="card bg-light mb-3">
	  <div class="card-body">
		{!!$dataTable->table() !!}
	  </div>
	</div>
	@include('partials.includes.formulaires.ajoutEtudiantForm',['idauditoireSelected'=>$auditoire->idauditoires])

</div>
@stop
@push('scripts')
{!!$dataTable->scripts() !!}
@endpush

resources/views/section/listeProfesseurs.blade.php
@extends('layouts.default')
@include('partials.includes.dataTables.dataTables')
@include('partials.includes.dataTables.buttons')
@section('content')
<div class="container">
	<div class="row">
        <div class="col-md-12">
         <h2 class="badge badge-pill badge-info">Liste des enseignant</h2>   
        </div>
    </div>
    <br>
    <button type="button" class="addModal btn btn-primary" data-toggle="modal" data-target="#editModal">
	  <span class="fas fa-plus"> </span> Ajouter enseignant
	</button>
	<br><br>
	<div class="card bg-light mb-3">
	  <div class="card-body">
		{!!$dataTable->table() !!}
	  </div>
	</div>
	@include('partials.includes.formulaires.ajoutProfForm')

</div>
@stop
@push('scripts')
{!!$dataTable->scripts() !!}


@endpush

resources/views/section/liste_auditoire.blade.php
@extends('layouts.default')
@include('partials.includes.dataTables.dataTables')
@include('partials.includes.dataTables.buttons')
@section('content')
<div class="container"  >
	<div class="row">
        <div class="col-md-12">
         <h2 class="badge badge-pill badge-info">Liste des auditoires</h2>   
        </div>
    </div>
    
     {{-- <hr /> --}}
	<div class="card bg-light mb-3">
	  <div class="card-body" >
		{!!$dataTable->table() !!}
	  </div>
	</div>
</div>	
@stop
@push('scripts')
{!!$dataTable->scripts() !!}
@endpush

resources/views/section/session_import.blade.php
@extends('layouts.default')
@section('content')
<div class="container"  >
	<div class="row">
        <div class="col-md-12">
         {{-- <h2 class="badge badge-pill badge-info">Liste des auditoires</h2>    --}}
        </div>
    </div>
    
     {{-- <hr /> --}}
		  
		  	@foreach($data as $d)
		    <div class="alert alert-dark" role="alert">
			  <a href="{{ route('section.get_session_import',$d->idtype_cotes) }}" class="btn btn-block " style="color: black">{!! strtoupper($d->lib) !!}</a>
			</div>
		    @endforeach
</div>	
@stop
@push('scripts')
@endpush