routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Route::get('/test', function () {
	$data =  App\Models\Cote::getFicheComplete(13);
	dd($data->get());																										
    return $data;
});

Route::get('/home', function(){
	if (auth()->check()) {
            $role = auth()->user()->users_roles;
            return redirect()->route($role.'.index');
        }
        
      return abort();
});

Route::get('/titulaires-login', 'Auth\TitulairesLoginController@showLoginForm')->name('prof-login');
Route::post('/titulaires-login', ['as'=> 'titulaires-login','uses'=>'Auth\TitulairesLoginController@login']);

/*|||||||||||||||||||||||||||||||||||||
|
|  Routes pour le professeur
|
|||||||||||||||||||||||||||||||||||||*/
Route::prefix('professeur')->group(function(){
	Route::name('professeur.')->group(function () {
		Route::get('/', 'Profs\DashboardController@index' )->name('index');
		Route::post('/redirect_fiche', 'Profs\DashboardController@redirectFiche' )->name('redirect_fiche');
		Route::get('/get_fiche/cours/{idcours}/{idtype_cotes}','Profs\DashboardController@getFiche')->name('get_fiche');
		Route::post('/set_cote','Profs\DashboardController@setCote')->name('set_cote');
		// Route::post('/send_fiche','Profs\DashboardController@sendFiche')->name('send_fiche');
		Route::get('/send_fiche/{type_cotes}/{cours}','Profs\DashboardController@sendFiche')->name('send_fiche');




		// Déconnexion prof
		Route::post('/prof-logout',function(){
			auth()->logout();
			return redirect()->route('prof-login');
		})->name('logout');
	});





	
});

/*|||||||||||||||||||||||||||||||||||||
|
|  Routes pour la section
|
|||||||||||||||||||||||||||||||||||||*/
Route::prefix('section')->group(function(){
	Route::name('section.')->group(function () {
		Route::get('/', 'Section\DashboardController@getListAuditoires')->name('index');
		// Session Import
		
		Route::get('/importation_cotes', 'Section\DashboardController@importSession')->name('session_import');
		Route::get('/importation_cotes/{type_cote}', 'Section\DashboardController@getImportSession')->name('get_session_import');
		Route::get('/importation_cote/{type_cote}/{auditoire}', 'Section\DashboardController@getImportSession')->name('get_session_import_by_auditoire');
		Route::get('/importation_fiche_cote', 'Section\DashboardController@getFicheImport')->name('get_fiche');
		
		// Etudiants
		Route::get('/etudiants', 'Section\DashboardController@getListAuditoiresEtudiants')->name('get_etudiants');
		Route::get('/get_etudiants_auditoires/{auditoire}', 'Section\DashboardController@getListStudent')->name('get_etudiants_by_auditoire');
		Route::resource('/gestion_etudiant', 'Gestions\EtudiantController')->only(['store']);


		// Cours
		Route::get('/get_cours_auditoires', 'Section\DashboardController@getListAuditoires')->name('get_cours');
		Route::get('/getCoursAuditoire/{auditoire}', 'Section\DashboardController@getCoursByAuditoire')->name('getCoursByAuditoire');
		Route::resource('/gestion_cours', 'Gestions\CoursController')->only(['store']);
		
		// Professeurs
		Route::get('/professeurs', 'Section\DashboardController@getListProfeseurs')->name('get_prof');
		Route::resource('/gestion_prof', 'Gestions\ProfController')->only(['store']);


	});
});

/*|||||||||||||||||||||||||||||||||||||
|
|  Routes pour le jury
|
|||||||||||||||||||||||||||||||||||||*/
Route::prefix('jury')->group(function(){
	Route::name('jury.')->group(function () {
		Route::get('/', 'Jury\DashboardController@index')->name('index');
		// Importation cotes
		Route::get('/importation_cotes', 'Jury\DashboardController@importSession')->name('session_import');
		Route::get('/importation_cotes/{type_cote}', 'Jury\DashboardController@getImportSession')->name('get_session_import');
		Route::get('/importation_cote/{type_cote}/{auditoire}', 'Jury\DashboardController@getCoursImportByAuditoire')->name('get_session_import_by_auditoire');
		Route::get('/importation_fiche_cote/{fiches_envoye}', 'Jury\DashboardController@getFicheImport')->name('get_fiche');
		

	});
});

Auth::routes();

resources/views/partials/includes/formulaires/_getAuditoires.blade.php
@inject('auditoires', 'App\Models\Auditoire')

<div class="form-group">
    <label class="col-sm-2 control-label">Auditoire</label>
    <div class="col-sm-12" id="audit">
        @php 
        $disabled = !empty($idauditoireSelected) ? 'disabled' : ''; @endphp
        <select class="form-control" id="fidauditoires" name="idauditoires" required="" {{ $disabled }}>
            @foreach($auditoires::getAuditoireGroupBySection() as $sections)
                <optgroup label="{{ $sections[0]->section_lib  }}">
                    @foreach ($sections as $auditoire)
                        @if(!empty($idauditoireSelected) && $idauditoireSelected == $auditoire->idauditoires)
                        <option value="{{ $auditoire->idauditoires }}" selected >{{ $auditoire->lib }}</option>
                        @else
                        <option value="{{ $auditoire->idauditoires }}"  >{{ $auditoire->lib }}</option>
                        @endif
                    @endforeach
                </optgroup>
            @endforeach
        </select>
    </div>
</div>

resources/views/partials/includes/formulaires/ajoutCoursForm.blade.php
@inject('titulaires', 'App\Models\Titulaire')

<div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Nouveau cours</h5>
        <button type="button" class="close"  data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        {{-- msg d'erreur --}}
        @include('partials._msgFlash')
        {{-- Formulaire --}}
        <form id="etudiantForm" action="{{ route('section.gestion_cours.store') }}" method="POST" name="etudiantForm" class="form-horizontal">
            @csrf
           <input type="hidden" name="idcours" id="fidcours">
           <input type="hidden" name="idauditoires" id="fidauditoires" value="{{ $auditoire->idauditoires }}">
            <div class="form-group">
                <label for="cours"  class="col-sm-2 control-label">Cours</label>
                <div class="col-sm-12">
                    <input type="text"  class="form-control" id="fcours" name="cours" placeholder="Entrer le nom du cours"  maxlength="100" required="required">
                </div>
            </div>
            <div class="form-group">
                <label for="ponderation"  class="col-sm-2 control-label">Ponderation</label>
                <div class="col-sm-12">
                    <input type="number" class="form-control" id="fponderation" name="ponderation" placeholder="Entrer la ponderation du cours"  maxlength="50" required="">
                </div>
            </div>
            <div class="form-group">
                <label for="ponderation"  class="col-sm-2 control-label">Titulaire</label>
                <div class="col-sm-12">
                    <select class="form-control" id="ftitulaire" name="titulaire">
                      <option></option>
                        @foreach($titulaires->get() as $titulaire)
                        <option value="{{ $titulaire->idtitulaires }}">{{ $titulaire->nom .' '. $titulaire->prenom }} </option>
                        @endforeach
                    </select>
                </div>
            </div>
            @include('partials.includes.formulaires._getAuditoires');
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
        <button type="submit" class="save btn btn-primary">Enregistrer</button>
      </div>
        </form>
    </div>
  </div>
</div>
@push('scripts')
<script type="text/javascript">
  {{-- Ajout étudiant formulaire --}}
  $(document).on('click', '.addModal', function() {
    $('#msgErrors').html('');
    $('#msgErrors').attr('hidden','true');

    $('.modal-title').text('Ajouter');
    resetmodalData()
    $('.form-horizontal_create').trigger("reset");
    $('.form-horizontal_create').show();
    $('#myModal').modal('show');
    });

  {{-- edition du formulaire --}}
  $(document).on('click', '.edit-modal', function() {
      $('#msgErrors').html('');
      $('#msgErrors').attr('hidden','true');
      $('#footer_action_button').text(" Update");
      $('#footer_action_button').addClass('fa fa-check');
      $('#footer_action_button').removeClass('fa fa-trash');
      $('.actionBtn').addClass('btn-success');
      $('.actionBtn').removeClass('btn-danger');
      $('.actionBtn').removeClass('delete');
      $('.actionBtn').addClass('edit');
      $('.modal-title').text('Modifier');
      $('.deleteContent').hide();
      $('.form-horizontal').show();
      var stuff = $(this).data('info').split(',');
      fillmodalData(stuff)
      $('#myModal').modal('show');
      });

  // remplissage formulaire par les donnée d'une ligne selectionée
  function fillmodalData(details){
      $('#fidcours').val(details[0]);
      $('#fcours').val(details[1]);
      $('#fponderation').val(details[2]);
      $('#ftitulaire').val(details[3]);
      $('#fidauditoires').val(details[4]);
     
      }

  function resetmodalData(){
      $('#fidcours').val('');
      $('#fcours').val('');
      $('#fponderation').val('');
      $('#ftitulaire').val('');
     
      }



  {{-- Suppression  --}}
  $(document).on('click', '.delete-modal', function() {
    $('#footer_action_button').text(" Delete");
    $('#footer_action_button').removeClass('glyphicon-check');
    $('#footer_action_button').addClass('glyphicon-trash');
    $('.actionBtn').removeClass('btn-success');
    $('.actionBtn').addClass('btn-danger');
    $('.actionBtn').removeClass('edit');
    $('.actionBtn').addClass('delete');
    $('.modal-title').text('Delete');
    $('.deleteContent').show();
    $('.form-horizontal').hide();
    var stuff = $(this).data('info').split(',');
    $('.divd').text(stuff[0]);
    $('.dname').html(stuff[1] +" "+stuff[2]);
    $('#myModal').modal('show');
  });

</script>
@endpush

resources/views/partials/includes/formulaires/ajoutEtudiantForm.blade.php
<!-- Modal -->
<div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterTitle">Modifier</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        {{-- msg d'erreur --}}
        @include('partials._msgFlash')
        {{-- Formulaire --}}
        <form id="etudiantForm" action="{{ route('section.gestion_etudiant.store') }}" method="POST" name="etudiantForm" class="form-horizontal">
            @csrf
           <input type="hidden" name="idetudiants" id="fidetudiants">
           <input type="hidden" name="idauditoires" id="idauditoires" value="<?= !empty($idauditoireSelected) ? $idauditoireSelected : '' ?>">
            <div class="form-group">
                <label for="matricule"  class="col-sm-2 control-label">Matricule</label>
                <div class="col-sm-12">
                    <input type="text" id="fmatricule" class="form-control" id="matricule" name="matricule" placeholder="Entrer matricule étudiant"  maxlength="50" required="required">
                </div>
            </div>
            <div class="form-group">
                <label for="nom"  class="col-sm-2 control-label">Nom</label>
                <div class="col-sm-12">
                    <input type="text" id="fnom" class="form-control" id="nom" name="nom" placeholder="Entrer nom étudiant"  maxlength="50" required="">
                </div>
            </div>
            <div class="form-group">
                <label for="postnom" class="col-sm-2 control-label">Postnom</label>
                <div class="col-sm-12">
                    <input type="text" id="fpostnom" class="form-control" id="postnom" name="postnom" placeholder="Entrer postnom étudiant"  maxlength="50" >
                </div>
            </div><div class="form-group">
                <label for="prenom"  class="col-sm-2 control-label">Prenom</label>
                <div class="col-sm-12">
                    <input type="text" id="fprenom" class="form-control" id="prenom" name="prenom" placeholder="Entrer prenom étudiant"  maxlength="50" >
                </div>
            </div>
            @include('partials.includes.formulaires._getAuditoires');
            
        {{--     <div class="col-sm-offset-2 col-sm-10">
             <button type="submit" class="btn btn-primary" id="saveBtn" value="create">Save changes
             </button>
            </div> --}}
	      <div class="modal-footer">
	        <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
	        <button type="submit" class="save btn btn-primary">Enregistrer</button>
	      </div>
        </form>
      </div>
    </div>
  </div>
</div>

@push('scripts')
<script type="text/javascript">
    
    {{-- Ajout étudiant formulaire --}}
    $(document).on('click', '.addModal', function() {
        $('#msgErrors').html('');
        $('#msgErrors').attr('hidden','true');

        $('.modal-title').text('Ajouter');
        resetmodalData()
        $('.form-horizontal').trigger("reset");
        $('.form-horizontal').show();
        $('#editModal').modal('show');
        });

    {{-- edition du formulaire --}}
    $(document).on('click', '.edit-modal', function() {
            $('#msgErrors').html('');
            $('#msgErrors').attr('hidden','true');

            $('#footer_action_button').text(" Update");
            $('#footer_action_button').addClass('fas fa-check');
            $('#footer_action_button').removeClass('fas fa-trash');
            $('.actionBtn').addClass('btn-success');
            $('.actionBtn').removeClass('btn-danger');
            $('.actionBtn').removeClass('delete');
            $('.actionBtn').addClass('edit');
            $('.modal-title').text('Modifier');
            $('.deleteContent').hide();
            $('.form-horizontal').show();
            var stuff = $(this).data('info').split(',');
            fillmodalData(stuff)
            $('#myModal').modal('show');
            });

    // remplissage formulaire par les donnée d'une ligne selectionée
    function fillmodalData(details){
            $('#fidetudiants').val(details[0]);
            $('#fmatricule').val(details[1]);
            $('#fnom').val(details[2]);
            $('#fpostnom').val(details[3]);
            $('#fprenom').val(details[4]);
            $('#fidauditoires').val(details[5]);
            // $('#fidauditoires').val(details[4]);
            // $('#gender').val(details[4]);
            // $('#country').val(details[5]);
            // $('#salary').val(details[6]);
            }

    function resetmodalData(){
            $('#fidetudiants').val('');
            $('#fmatricule').val('');
            $('#fnom').val('');
            $('#fpostnom').val('');
            $('#fprenom').val('');
            // $('#fidauditoires').val('');
            // $('#gender').val(details[4]);
            // $('#country').val(details[5]);
            // $('#salary').val(details[6]);
            }



    $('#etudiantForm').on('submit', function(e) {
        e.preventDefault();
        $('#msgErrors').html('');
        $('#msgErrors').attr('hidden','true');

        $.ajax({
            type: 'post',
            url: '{{ route('section.gestion_etudiant.store') }}',
            data: {
                '_token': $('input[name=_token]').val(),
                'idetudiants': $("#fidetudiants").val(),
                'matricule': $("#fmatricule").val(),
                'nom': $('#fnom').val(),
                'postnom': $('#fpostnom').val(),
                'prenom': $('#fprenom').val(),
                'idauditoires': $('#fidauditoires').val(),
                // 'gender': $('#gender').val(),
                // 'country': $('#country').val(),  
                // 'salary': $('#salary').val()
                },

            success: function(data) {
                $('#dataTableBuilder').DataTable().draw(false);
                $('#editModal').modal('hide');
                
            },

            error:function(data) {
                var errors = data.responseJSON.errors;
                  $.each(errors, function (key, value) {
                    document.getElementById('msgErrors').innerHTML += "<li>"+value+"</li>"
                    $('#msgErrors').removeAttr('hidden');
                });
            }
        });
    });

    {{-- Suppression  --}}
    $(document).on('click', '.delete-modal', function() {
        $('#footer_action_button').text(" Delete");
        $('#footer_action_button').removeClass('glyphicon-check');
        $('#footer_action_button').addClass('glyphicon-trash');
        $('.actionBtn').removeClass('btn-success');
        $('.actionBtn').addClass('btn-danger');
        $('.actionBtn').removeClass('edit');
        $('.actionBtn').addClass('delete');
        $('.modal-title').text('Delete');
        $('.deleteContent').show();
        $('.form-horizontal').hide();
        var stuff = $(this).data('info').split(',');
        $('.did').text(stuff[0]);
        $('.dname').html(stuff[1] +" "+stuff[2]);
        $('#myModal').modal('show');
    });

</script>
@endpush

resources/views/partials/includes/formulaires/ajoutProfForm.blade.php
<!-- Modal -->
<div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterTitle">Modifier</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        {{-- msg d'erreur --}}
        @include('partials._msgFlash')
        {{-- Formulaire --}}
        <form id="profForm" action="{{ route('section.gestion_prof.store') }}" method="POST" name="profForm" class="form-horizontal">
            @csrf
           <input type="hidden" name="idtitulaires" id="fidtitulaires">
            <div class="form-group">
                <label for="matricule"  class="col-sm-2 control-label">Matricule</label>
                <div class="col-sm-12">
                    <input type="text" id="fmatricule" class="form-control" id="matricule" name="matricule" placeholder="Entrer matricule étudiant"  maxlength="50" required="required">
                </div>
            </div>
            <div class="form-group">
                <label for="nom"  class="col-sm-2 control-label">Nom</label>
                <div class="col-sm-12">
                    <input type="text" id="fnom" class="form-control" id="nom" name="nom" placeholder="Entrer nom étudiant"  maxlength="50" required="">
                </div>
            </div>
            <div class="form-group">
                <label for="postnom" class="col-sm-2 control-label">Postnom</label>
                <div class="col-sm-12">
                    <input type="text" id="fpostnom" class="form-control" id="postnom" name="postnom" placeholder="Entrer postnom étudiant"  maxlength="50" >
                </div>
            </div>
            <div class="form-group">
                <label for="prenom"  class="col-sm-2 control-label">Prenom</label>
                <div class="col-sm-12">
                    <input type="text" id="fprenom" class="form-control" id="prenom" name="prenom" placeholder="Entrer prenom étudiant"  maxlength="50" >
                </div>
            </div>
            @include('partials.includes.formulaires._getAuditoires');
           
        {{--     <div class="col-sm-offset-2 col-sm-10">
             <button type="submit" class="btn btn-primary" id="saveBtn" value="create">Save changes
             </button>
            </div> --}}
	      <div class="modal-footer">
	        <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
	        <button type="submit" class="save btn btn-primary">Enregistrer</button>
	      </div>
        </form>
      </div>
    </div>
  </div>
</div>

@push('scripts')
<script type="text/javascript">
    
    {{-- Ajout étudiant formulaire --}}
    $(document).on('click', '.addModal', function() {
        $('#msgErrors').html('');
        $('#msgErrors').attr('hidden','true');

        $('.modal-title').text('Ajouter');
        resetmodalData()
        $('.form-horizontal').trigger("reset");
        $('.form-horizontal').show();
        $('#myModal').modal('show');
        });

    {{-- edition du formulaire --}}
    $(document).on('click', '.edit-modal', function() {
            $('#msgErrors').html('');
            $('#msgErrors').attr('hidden','true');

            $('#footer_action_button').text(" Update");
            $('#footer_action_button').addClass('fas fa-check');
            $('#footer_action_button').removeClass('fas fa-trash');
            $('.actionBtn').addClass('btn-success');
            $('.actionBtn').removeClass('btn-danger');
            $('.actionBtn').removeClass('delete');
            $('.actionBtn').addClass('edit');
            $('.modal-title').text('Modifier');
            $('.deleteContent').hide();
            $('.form-horizontal').show();
            var stuff = $(this).data('info').split(',');
            fillmodalData(stuff)
            $('#myModal').modal('show');
            });

    // remplissage formulaire par les donnée d'une ligne selectionée
    function fillmodalData(details){
            $('#fidtitulaires').val(details[0]);
            $('#fmatricule').val(details[1]);
            $('#fnom').val(details[2]);
            $('#fpostnom').val(details[3]);
            $('#fprenom').val(details[4]);
            $('#fidauditoires').val(details[5]);
            // $('#fidauditoires').val(details[4]);
            // $('#gender').val(details[4]);
            // $('#country').val(details[5]);
            // $('#salary').val(details[6]);
            }

    function resetmodalData(){
            $('#fidtitulaires').val('');
            $('#fmatricule').val('');
            $('#fnom').val('');
            $('#fpostnom').val('');
            $('#fprenom').val('');
            // $('#fidauditoires').val('');
            // $('#gender').val(details[4]);
            // $('#country').val(details[5]);
            // $('#salary').val(details[6]);
            }



    $('#profForm').on('submit', function(e) {
        e.preventDefault();
        $('#msgErrors').html('');
        $('#msgErrors').attr('hidden','true');

        $.ajax({
            type: 'post',
            url: '{{ route('section.gestion_prof.store') }}',
            data: {
                '_token': $('input[name=_token]').val(),
                'idtitulaires': $("#fidtitulaires").val(),
                'matricule': $("#fmatricule").val(),
                'nom': $('#fnom').val(),
                'postnom': $('#fpostnom').val(),
                'prenom': $('#fprenom').val(),
                'idauditoires': $('#fidauditoires').val(),
                // 'gender': $('#gender').val(),
                // 'country': $('#country').val(),  
                // 'salary': $('#salary').val()
                },

            success: function(data) {
                $('#dataTableBuilder').DataTable().draw(false);
                $('#editModal').modal('hide');
                
            },

            error:function(data) {
                var errors = data.responseJSON.errors;
                  $.each(errors, function (key, value) {
                    document.getElementById('msgErrors').innerHTML += "<li>"+value+"</li>"
                    $('#msgErrors').removeAttr('hidden');
                });
            }
        });
    });

    {{-- Suppression  --}}
    $(document).on('click', '.delete-modal', function() {
        $('#footer_action_button').text(" Delete");
        $('#footer_action_button').removeClass('glyphicon-check');
        $('#footer_action_button').addClass('glyphicon-trash');
        $('.actionBtn').removeClass('btn-success');
        $('.actionBtn').addClass('btn-danger');
        $('.actionBtn').removeClass('edit');
        $('.actionBtn').addClass('delete');
        $('.modal-title').text('Delete');
        $('.deleteContent').show();
        $('.form-horizontal').hide();
        var stuff = $(this).data('info').split(',');
        $('.did').text(stuff[0]);
        $('.dname').html(stuff[1] +" "+stuff[2]);
        $('#myModal').modal('show');
    });

</script>
@endpush