routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Route::get('/test', function () {
	$data =  App\Models\Cote::getFicheComplete(13);
	dd($data->get());																										
    return $data;
});

Route::get('/home', function(){
	if (auth()->check()) {
            $role = auth()->user()->users_roles;
            return redirect()->route($role.'.index');
        }
        
      return abort();
});

Route::get('/titulaires-login', 'Auth\TitulairesLoginController@showLoginForm')->name('prof-login');
Route::post('/titulaires-login', ['as'=> 'titulaires-login','uses'=>'Auth\TitulairesLoginController@login']);

/*|||||||||||||||||||||||||||||||||||||
|
|  Routes pour le professeur
|
|||||||||||||||||||||||||||||||||||||*/
Route::prefix('professeur')->group(function(){
	Route::name('professeur.')->group(function () {
		Route::get('/', 'Profs\DashboardController@index' )->name('index');
		Route::post('/redirect_fiche', 'Profs\DashboardController@redirectFiche' )->name('redirect_fiche');
		Route::get('/get_fiche/cours/{idcours}/{idtype_cotes}','Profs\DashboardController@getFiche')->name('get_fiche');
		Route::post('/set_cote','Profs\DashboardController@setCote')->name('set_cote');
		// Route::post('/send_fiche','Profs\DashboardController@sendFiche')->name('send_fiche');
		Route::get('/send_fiche/{type_cotes}/{cours}','Profs\DashboardController@sendFiche')->name('send_fiche');




		// Déconnexion prof
		Route::post('/prof-logout',function(){
			auth()->logout();
			return redirect()->route('prof-login');
		})->name('logout');
	});





	
});

/*|||||||||||||||||||||||||||||||||||||
|
|  Routes pour la section
|
|||||||||||||||||||||||||||||||||||||*/
Route::prefix('section')->group(function(){
	Route::name('section.')->group(function () {
		Route::get('/', 'Section\DashboardController@getListAuditoires')->name('index');
		// Session Import
		
		Route::get('/importation_cotes', 'Section\DashboardController@importSession')->name('session_import');
		Route::get('/importation_cotes/{type_cote}', 'Section\DashboardController@getImportSession')->name('get_session_import');
		Route::get('/importation_cote/{type_cote}/{auditoire}', 'Section\DashboardController@getImportSession')->name('get_session_import_by_auditoire');
		Route::get('/importation_fiche_cote', 'Section\DashboardController@getFicheImport')->name('get_fiche');
		
		// Etudiants
		Route::get('/etudiants', 'Section\DashboardController@getListAuditoiresEtudiants')->name('get_etudiants');
		Route::get('/get_etudiants_auditoires/{auditoire}', 'Section\DashboardController@getListStudent')->name('get_etudiants_by_auditoire');
		Route::resource('/gestion_etudiant', 'Gestions\EtudiantController')->only(['store']);


		// Cours
		Route::get('/get_cours_auditoires', 'Section\DashboardController@getListAuditoires')->name('get_cours');
		Route::get('/getCoursAuditoire/{auditoire}', 'Section\DashboardController@getCoursByAuditoire')->name('getCoursByAuditoire');
		Route::resource('/gestion_cours', 'Gestions\CoursController')->only(['store']);
		
		// Professeurs
		Route::get('/professeurs', 'Section\DashboardController@getListProfeseurs')->name('get_prof');
		Route::resource('/gestion_prof', 'Gestions\ProfController')->only(['store']);


	});
});

/*|||||||||||||||||||||||||||||||||||||
|
|  Routes pour le jury
|
|||||||||||||||||||||||||||||||||||||*/
Route::prefix('jury')->group(function(){
	Route::name('jury.')->group(function () {
		Route::get('/', 'Jury\DashboardController@index')->name('index');
		// Importation cotes
		Route::get('/importation_cotes', 'Jury\DashboardController@importSession')->name('session_import');
		Route::get('/importation_cotes/{type_cote}', 'Jury\DashboardController@getImportSession')->name('get_session_import');
		Route::get('/importation_cote/{type_cote}/{auditoire}', 'Jury\DashboardController@getCoursImportByAuditoire')->name('get_session_import_by_auditoire');
		Route::get('/importation_fiche_cote/{fiches_envoye}', 'Jury\DashboardController@getFicheImport')->name('get_fiche');
		

	});
});

Auth::routes();

app/Http/Controllers/Gestions/ProfController.php
<?php

namespace App\Http\Controllers\Gestions;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\CRUDProfRequest;
use App\Models\Titulaire;
use Flashy;

class ProfController extends Controller
{
     /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CRUDProfRequest $request)
    {
    	// dd($request);
        Titulaire::updateOrCreate([
                                    'idtitulaires' => $request->idtitulaires
                                ],
                                [
                                    'matricule' => $request->matricule,
                                    'nom' => $request->nom,
                                    'postnom' => $request->postnom,
                                    'prenom' => $request->prenom, 
                                    'idgrades' => $request->idgrades ? $request->idgrades :1, 
                                ]); 
       
        Flashy::success('Opération éffectuée avec succès');
        return redirect()->back();          
    }
}

app/Http/Controllers/Profs/DashboardController.php
<?php

namespace App\Http\Controllers\Profs;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\DataTables\Profs\ListCoursByProfDataTable;
use App\DataTables\Profs\FicheCotesDataTable;
use App\Http\Requests\RedirectFicheRequest;
use App\Http\Requests\SetCoteRequest;
use App\Http\Requests\SendFicheRequest;
use App\Models\Cour;
use App\Models\Type_cote;
use App\Models\Auditoire;
use App\Models\Titulaire;
use App\Models\Cote;
use App\Models\Fiches_envoye;


class DashboardController extends Controller
{
	/**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth:titulaires');
    }

    // Affiche la liste des cours attribué au titulaire connecter
    public function index(ListCoursByProfDataTable $dataTables){
    	return $dataTables->with(['idtitulaires'=>auth()->user()->idtitulaires])->render('profs.index');
    }

    // genere le lien de fiche selon le type de cote

    public function redirectFiche(RedirectFicheRequest $request){

        return route('professeur.get_fiche',['idcours'=>$request->cours,'idtype_cote'=>$request->session]);
    }
    /**
     * retourne la fiche de cotes d'un cours 
     * @param $idcours
     * @param $type_cotes
     * @return dataTable
     */
    public function getFiche(Cour $idcours,Type_cote $idtype_cotes,FicheCotesDataTable $dataTables){
        if (auth()->user()->idtitulaires == $idcours->idtitulaires) {
            $auditoire = Auditoire::find($idcours->idauditoires);
            $prof = Titulaire::find($idcours->idtitulaires);

            return $dataTables->with(['idcours'=>$idcours->idcours,'idtype_cotes'=>$idtype_cotes->idtype_cotes,'idauditoires'=>$auditoire->idauditoires])->render('profs.fiche_cotation',compact('auditoire','prof','idcours','idtype_cotes'));
           
        }

        return abort(401);
    }

    /**
     * retourne la fiche de cotes d'un cours 
     * @param $idcours
     * @param $type_cotes
     * @return dataTable
     */
    public function sendFiche(Type_cote $type_cotes,Cour $cours){
       Fiches_envoye::create([
        'idcours'=>$cours->idcours,
        'idtype_cotes'=>$type_cotes->idtype_cotes,
       ]);
      return redirect()->back();     

    }

    /**
     * retourne la fiche de cotes d'un cours 
     * @param $idcours
     * @param $type_cotes
     * @return dataTable
     */
    public function setCote(SetCoteRequest $request){
        // dd($request->request);
        return Cote::updateOrCreate(
                        [
                            'idcotes' => $request->idcotes,

                        ],
                        [
                            'idetudiants' => $request->idetudiants,
                            'idcours' => $request->idcours,
                            'idtype_cotes' => $request->idtype_cotes,
                            'cote' => $request->cote,

                        ]
                     );
    }
}

resources/views/profs/fiche_cotation.blade.php
@extends('layouts.master-prof')
@include('partials.includes.dataTables.dataTables')
@include('partials.includes.dataTables.buttons')
@section('content')
	<div class="card">
	  <div class="card-header">
	  	Titulaire : {{ $prof->nom .' '.$prof->prenom }}
	  	<br>
	  	Promotion : {{ $auditoire->lib }}
	  	<br>
	  	Cours : {{ $idcours->lib }}
	  	<br>
	  	Max : {{ $idcours->ponderation }}
	  	<br>
	  	<h5><span class="badge badge-pill badge-secondary">Fiche de l' {!! $idtype_cotes->lib !!}</span></h5>
	  </div>
	  <div class="card-body">
	  	{!!$dataTable->table() !!}

	  </div>
	  @if(!App\Models\Fiches_envoye::isSended($idtype_cotes->idtype_cotes,$idcours->idcours))
	  <div class="card-footer text-center">
		<a href="#" id="send-fiche" class="btn btn-primary btn-block">Envoyer la fiche</a>
	  </div>
	  @endif
	</div>
	
	

	<!-- Modal -->
	<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true" >
	  <div class="modal-dialog modal-dialog-centered" role="document">
	    <div class="modal-content">
		     {{--  <div class="modal-header">
		        <h5 class="modal-title" id="exampleModalCenterTitle">Modal title</h5>
		        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
		          <span aria-hidden="true">&times;</span>
		        </button>
		      </div> --}}
	            <div class="modal-body">
	    <div class="deleteContent" >
	    	<div class="alert alert-warning" role="alert">
              <h4 class="alert-heading">Envoyer la fiche de cotes!</h4>
              <p>Lorsque vous validez, les cotes seront accèssibles par la section et le bureau du jury à l'instant.</p>
              <hr>
              <p class="mb-0">Vous ne pouvez plus modifier les cotes après l'envoi!.</p>
            </div>
	    </div>
        {{-- msg d'erreur --}}
        @include('partials._msgFlash')
        {{-- Formulaire --}}
        <form id="cote-form" action="{{ route('professeur.set_cote') }}" method="POST" name="cote-form" class="form-horizontal">
            @csrf
           <input type="text" name="idcotes" id="fidcotes" style="display: none">
           <input type="text" name="idetudiants" id="fidetudiants" required="" style="display: none">
           <input type="text" name="idcours" id="fidcours" value="{{ $idcours->idcours }}" required="" style="display: none">
           <input type="hidden" name="idtype_cotes" id="fidtype_cotes" value="{{ $idtype_cotes->idtype_cotes }}" required="">
           {{-- <input type="hidden" name="idcotes" id="idcotes" value="{{ $auditoire->idauditoires }}"> --}}
           <div class="form-group">
                <label for="nom"  class="col-sm-12 control-label">Nom de l'étudiant</label>
                <div class="col-sm-12">
                    <input type="text" class="form-control disable" id="fnom" name="nom" placeholder=""  disabled="">
                </div>
            </div>
            <div class="form-group">
                <label for="Note"  class="col-sm-2 control-label">Note</label>
                <div class="col-sm-12">
                    <input type="number" class="form-control" id="fcote" name="cote" placeholder="Entrer la Note "  maxlength="50" max="{{ $idcours->ponderation }}" required="" autofocus>
                </div>
            </div>
            
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
        <a href="{{ route('professeur.send_fiche',['type_cotes'=>$idtype_cotes->idtype_cotes,'cours'=>$idcours->idcours]) }}" class="send_fiche btn btn-primary invisible">Envoyer</a>
        <button type="submit" class="actionBtn save btn btn-primary">Valider</button>
      </div>
        </form>
    </div>
	   
	    </div>
	  </div>
	</div>

@endsection
@push('scripts')
	{!!$dataTable->scripts() !!}

	<script type="text/javascript">
		{{-- edition du formulaire --}}
	$(document).on('click', '.link-cote', function() {
			$('#msgErrors').html('');
      		$('#msgErrors').attr('hidden','true');
      		$('.deleteContent').attr('hidden','true');

			$('#footer_action_button').text(" Update");
			$('#footer_action_button').addClass('fas fa-check');
			$('#footer_action_button').removeClass('fas fa-trash');
			$('.actionBtn').addClass('btn-primary');
			$('.actionBtn').removeClass('btn-danger');
			$('.actionBtn').removeClass('invisible');
			$('.send_fiche').addClass('invisible');
			$('.actionBtn').addClass('edit');
			$('.modal-title').text('Modifier');


			$('.form-horizontal').show();
			var stuff = $(this).data('info').split(',');
			fillmodalData(stuff)
			$('#myModal').modal('show');
			});

	// remplissage formulaire par les donnée d'une ligne selectionée
	function fillmodalData(details){
			$('#fidcotes').val(details[0]);
			$('#fcote').val(details[1]);
			$('#fidetudiants').val(details[2]);
			$('#fnom').val(details[3]);
			
			}

	$('#cote-form').on('submit', function(e) {
		e.preventDefault();
		$('#msgErrors').html('');
      	$('#msgErrors').attr('hidden','true');

		$.ajax({
			type: 'post',
			url: '{{ route('professeur.set_cote') }}',
			data: {
				'_token': $('input[name=_token]').val(),
				'idcotes': $("#fidcotes").val(),
				'idetudiants': $("#fidetudiants").val(),
				'idcours': $('#fidcours').val(),
				'idtype_cotes': $('#fidtype_cotes').val(),
				'cote': $('#fcote').val(),
				// 'prenom': $('#fprenom').val(),
				// 'idauditoires': $('#fidauditoires').val(),
				
				},

			success: function(data) {
				$('#dataTableBuilder').DataTable().draw(false);
				$('.modal').modal('hide');
				
			},

	        error:function(data) {
		        var errors = data.responseJSON.errors;
		          $.each(errors, function (key, value) {
		          	document.getElementById('msgErrors').innerHTML += "<li>"+value+"</li>"
		            $('#msgErrors').removeAttr('hidden');
		        });
		    }
		});
	});
	$('#send-fiche').on('click', function(e) {
		e.preventDefault();
      	$('.deleteContent').removeAttr('hidden','false');
		$('#footer_action_button').text("Delete");
		$('#footer_action_button').removeClass('glyphicon-check');
		$('#footer_action_button').addClass('glyphicon-trash');
		$('.actionBtn').removeClass('btn-primary');
		$('.actionBtn').addClass('btn-danger');
		$('.actionBtn').removeClass('edit');
		$('.actionBtn').addClass('invisible');
		$('.send_fiche').removeClass('invisible');
		$('.modal-title').text('Delete');
		$('.deleteContent').show();
		$('.form-horizontal').hide();
		$('#exampleModalCenter').modal('show');
		});
	$('.send').on('click', function(e) {
		e.preventDefault();
		alert('k,');
		$('#msgErrors').html('');
      	$('#msgErrors').attr('hidden','true');

		$.ajax({
			type: 'post',
			url: '#',
			data: {
				'_token': $('input[name=_token]').val(),
				'idcours': $('#fidcours').val(),
				'idtype_cotes': $('#fidtype_cotes').val(),
				
				},

			success: function(data) {
				$('.modal').modal('hide');
				
			},

	        error:function(data) {
		        var errors = data.responseJSON.errors;
		          $.each(errors, function (key, value) {
		          	document.getElementById('msgErrors').innerHTML += "<li>"+value+"</li>"
		            $('#msgErrors').removeAttr('hidden');
		        });
		    }
		});
	});
	</script>

	
@endpush

resources/views/profs/index.blade.php
@extends('layouts.master-prof')
@include('partials.includes.dataTables.dataTables')
@include('partials.includes.dataTables.buttons')
@section('content')
	<div class="card">
	  <div class="card-header">
	  	{{ auth()->user()->nom .' '. auth()->user()->prenom}}
	  	<br>
	  	
	  </div>
		<div class="card-body">
			{!!$dataTable->table() !!}
		</div>
	</div>
	

	<!-- Modal -->
	<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
	  <div class="modal-dialog modal-dialog-centered" role="document">
	    <div class="modal-content">
		     {{--  <div class="modal-header">
		        <h5 class="modal-title" id="exampleModalCenterTitle">Modal title</h5>
		        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
		          <span aria-hidden="true">&times;</span>
		        </button>
		      </div> --}}
	      <div class="modal-body">
	        @inject('type_cotes','App\Models\Type_cote')
	        <div class="container">
	        	@foreach($type_cotes->get() as $tc)
	        	<a href="#" data-type_cote="{{ $tc->idtype_cotes  }}" class="link-cours btn btn-info btn-block">{!! $tc->lib !!}</a>
	        	@endforeach
	        </div>
	      </div>
	      {{-- <div class="modal-footer">
	        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
	        <button type="button" class="btn btn-primary">Save changes</button>
	      </div> --}}
	    </div>
	  </div>
	</div>

@endsection
@push('scripts')
	{!!$dataTable->scripts() !!}
	<script type="text/javascript">
		idcours = 0;
		$(document).on('click','.fiche-cote', function() {
		var field = $(this).data('info').split(',');
		idcours = field[0];
		var link = $('.link-cours');
		
	});

		$(document).on('click','.link-cours',function(e){
			e.preventDefault();
			var idtype_cotes = $(this).data('type_cote');
			$.ajax({
			type: 'post',
			url: '{{ route("professeur.redirect_fiche") }}',
			data: {
				'_token': $('input[name=_token]').val(),
				'cours': idcours,
				'session': idtype_cotes,
				},

			success: function(data) {
				location = data
				
			},

	        error:function(data) {
		        var errors = data.responseJSON.errors;
		          $.each(errors, function (key, value) {
		          	document.getElementById('msgErrors').innerHTML += "<li>"+value+"</li>"
		            $('#msgErrors').removeAttr('hidden');
		        });
		    }
		});
		});
	</script>
@endpush