routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Route::get('/test', function () {
	$data =  App\Models\Cote::getFicheComplete(13);
	dd($data->get());																										
    return $data;
});

Route::get('/home', function(){
	if (auth()->check()) {
            $role = auth()->user()->users_roles;
            return redirect()->route($role.'.index');
        }
        
      return abort();
});

Route::get('/titulaires-login', 'Auth\TitulairesLoginController@showLoginForm')->name('prof-login');
Route::post('/titulaires-login', ['as'=> 'titulaires-login','uses'=>'Auth\TitulairesLoginController@login']);

/*|||||||||||||||||||||||||||||||||||||
|
|  Routes pour le professeur
|
|||||||||||||||||||||||||||||||||||||*/
Route::prefix('professeur')->group(function(){
	Route::name('professeur.')->group(function () {
		Route::get('/', 'Profs\DashboardController@index' )->name('index');
		Route::post('/redirect_fiche', 'Profs\DashboardController@redirectFiche' )->name('redirect_fiche');
		Route::get('/get_fiche/cours/{idcours}/{idtype_cotes}','Profs\DashboardController@getFiche')->name('get_fiche');
		Route::post('/set_cote','Profs\DashboardController@setCote')->name('set_cote');
		// Route::post('/send_fiche','Profs\DashboardController@sendFiche')->name('send_fiche');
		Route::get('/send_fiche/{type_cotes}/{cours}','Profs\DashboardController@sendFiche')->name('send_fiche');




		// Déconnexion prof
		Route::post('/prof-logout',function(){
			auth()->logout();
			return redirect()->route('prof-login');
		})->name('logout');
	});





	
});

/*|||||||||||||||||||||||||||||||||||||
|
|  Routes pour la section
|
|||||||||||||||||||||||||||||||||||||*/
Route::prefix('section')->group(function(){
	Route::name('section.')->group(function () {
		Route::get('/', 'Section\DashboardController@getListAuditoires')->name('index');
		// Session Import
		
		Route::get('/importation_cotes', 'Section\DashboardController@importSession')->name('session_import');
		Route::get('/importation_cotes/{type_cote}', 'Section\DashboardController@getImportSession')->name('get_session_import');
		Route::get('/importation_cote/{type_cote}/{auditoire}', 'Section\DashboardController@getImportSession')->name('get_session_import_by_auditoire');
		Route::get('/importation_fiche_cote', 'Section\DashboardController@getFicheImport')->name('get_fiche');
		
		// Etudiants
		Route::get('/etudiants', 'Section\DashboardController@getListAuditoiresEtudiants')->name('get_etudiants');
		Route::get('/get_etudiants_auditoires/{auditoire}', 'Section\DashboardController@getListStudent')->name('get_etudiants_by_auditoire');
		Route::resource('/gestion_etudiant', 'Gestions\EtudiantController')->only(['store']);


		// Cours
		Route::get('/get_cours_auditoires', 'Section\DashboardController@getListAuditoires')->name('get_cours');
		Route::get('/getCoursAuditoire/{auditoire}', 'Section\DashboardController@getCoursByAuditoire')->name('getCoursByAuditoire');
		Route::resource('/gestion_cours', 'Gestions\CoursController')->only(['store']);
		
		// Professeurs
		Route::get('/professeurs', 'Section\DashboardController@getListProfeseurs')->name('get_prof');
		Route::resource('/gestion_prof', 'Gestions\ProfController')->only(['store']);


	});
});

/*|||||||||||||||||||||||||||||||||||||
|
|  Routes pour le jury
|
|||||||||||||||||||||||||||||||||||||*/
Route::prefix('jury')->group(function(){
	Route::name('jury.')->group(function () {
		Route::get('/', 'Jury\DashboardController@index')->name('index');
		// Importation cotes
		Route::get('/importation_cotes', 'Jury\DashboardController@importSession')->name('session_import');
		Route::get('/importation_cotes/{type_cote}', 'Jury\DashboardController@getImportSession')->name('get_session_import');
		Route::get('/importation_cote/{type_cote}/{auditoire}', 'Jury\DashboardController@getCoursImportByAuditoire')->name('get_session_import_by_auditoire');
		Route::get('/importation_fiche_cote/{fiches_envoye}', 'Jury\DashboardController@getFicheImport')->name('get_fiche');
		

	});
});

Auth::routes();

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/default.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}" dir="ltr">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="Bil Wifi" content="{{ config('app.name') }} by KinDev">
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href={{ asset('favicon.ico') }}>
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ !empty ($title) ? $title .' | '. config('app.name') : config('app.name') }}  </title>

    @yield('stylesheet1')
        <!-- Custom CSS -->
    <link href="{{ asset('bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ asset('css/dashboard.css') }}" rel="stylesheet">
    <link href="{{ asset('bootstrap/icons/font-awesome/css/fontawesome-all.css') }}" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    @yield('stylesheet')
    <!-- Coustom styleSheet--->
    @stack('stylesheets')


</head>
  <body>
    <nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
      <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="
      #">TCotes | ISPT</a>
      <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
      <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
          <a href="{{ route('logout') }}" onclick="event.preventDefault();document.getElementById('logout-form').submit();" class="btn btn-danger square-btn-adjust">Déconnexion</a>
            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                @csrf
            </form>
        </li>
      </ul>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
          <div class="sidebar-sticky">
            <ul class="nav flex-column">
                <li class="text-center mx-auto d-block sidebar-item">
                    <img style="max-width: 60%" src="{{ asset('/img/tcote.png') }}" class="user-image rounded-circle img-responsive img-fluid"/>
                </li>
                <br>
             
    @if(auth()->user()->users_roles == 'section')
              <li class="nav-item">
                <a class="nav-link btn btn-outline-primary btn-lg btn-block active" href="{{ route('section.session_import') }}">
                  <span data-feather="home"></span>
                  Tableau de bord <span class="sr-only">(current)</span>
                </a>
              </li>
              <br>
              <li class="nav-item">
                <a class="nav-link btn btn-outline-primary btn-lg btn-block active" href="{{ route('section.get_etudiants') }}">
                  <span data-feather="home"></span>
                  Etudiants <span class="sr-only">(current)</span>
                </a>
              </li>
              <br>
              <li class="nav-item">
                <a class="nav-link btn btn-outline-primary btn-lg btn-block active" href="{{ route('section.get_cours') }}">
                  <span data-feather="home"></span>
                  Cours <span class="sr-only">(current)</span>
                </a>
              </li>
              <br>
              <li class="nav-item">
                <a class="nav-link btn btn-outline-primary btn-lg btn-block active" href="{{ route('section.get_prof') }}">
                  <span data-feather="home"></span>
                  Professeurs <span class="sr-only">(current)</span>
                </a>
              </li>

    @elseif (auth()->user()->users_roles == 'jury') 
    <li class="nav-item">
                <a class="nav-link btn btn-outline-primary btn-lg btn-block active" href="{{ route('jury.index') }}">
                  <span data-feather="home"></span>
                  Tableau de bord <span class="sr-only">(current)</span>
                </a>
              </li>
                
    @endif
             
              
            </ul>
          </div>
        </nav>

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h3">Tableau de bord</h1>
            {{-- <div class="btn-toolbar mb-2 mb-md-0">
              <div class="btn-group mr-2">
                <button class="btn btn-sm btn-outline-secondary">Share</button>
                <button class="btn btn-sm btn-outline-secondary">Export</button>
              </div>
              <button class="btn btn-sm btn-outline-secondary dropdown-toggle">
                <span data-feather="calendar"></span>
                This week
              </button>
            </div> --}}
          </div>

          {{-- <canvas class="my-4 w-100" id="myChart" width="900" height="380"></canvas> --}}

          @yield('content')
          @include('layouts.partials._footer')

        </main>
      </div>
    </div>
     <!-- SCRIPTS -AT THE BOTOM TO REDUCE THE LOAD TIME-->
    <!-- JQUERY SCRIPTS -->
    <script src={{ asset('backend/assets/libs/jquery/dist/jquery.min.js') }}></script>

      <!-- BOOTSTRAP SCRIPTS -->
    <script src={{ asset('backend/assets/libs/bootstrap/dist/js/bootstrap.min.js') }}></script>
    <script src={{ asset('bootstrap/js/bootstrap.bundle.min.js') }}></script>
    {{-- <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="../../assets/js/vendor/jquery-slim.min.js" ></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="../../assets/js/vendor/popper.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
 --}}
    <!-- Icons -->
    <script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
    <script>
      feather.replace()
    </script>

    <!-- Graphs -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js"></script>
    <script>
      var ctx = document.getElementById("myChart");
      var myChart = new Chart(ctx, {
        type: 'line',
        data: {
          labels: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
          datasets: [{
            data: [15339, 21345, 18483, 24003, 23489, 24092, 12034],
            lineTension: 0,
            backgroundColor: 'transparent',
            borderColor: '#007bff',
            borderWidth: 4,
            pointBackgroundColor: '#007bff'
          }]
        },
        options: {
          scales: {
            yAxes: [{
              ticks: {
                beginAtZero: false
              }
            }]
          },
          legend: {
            display: false,
          }
        }
      });
    </script>
    @stack('scripts')
    @include('flashy::message')

  </body>

<!-- Mirrored from getbootstrap.com/docs/4.1/examples/dashboard/ by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 07 Nov 2018 23:41:52 GMT -->
</html>

resources/views/layouts/master-prof.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}" dir="ltr">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="Bil Wifi" content="{{ config('app.name') }} by KinDev">
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href={{ asset('favicon.ico') }}>
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ !empty ($title) ? $title .' | '. config('app.name') : config('app.name') }}  </title>
  <!-- BOOTSTRAP STYLES-->
    <link href="{{ asset('bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
    {{-- <link href="{{ asset('css/bootstrap.css') }}" rel="stylesheet"> --}}
    @yield('stylesheet1')
     <!-- FONTAWESOME STYLES-->
        <!-- Custom CSS -->
    <link href="{{ asset('bootstrap/icons/font-awesome/css/fontawesome-all.css') }}" rel="stylesheet">
     <!-- MORRIS CHART STYLES-->
    <style type="text/css">
      body {
          padding-top: 5rem;
        }
      .starter-template {
          /*padding: 3rem 1.5rem;*/
        }
    </style>
        <!-- CUSTOM STYLES-->
    {{-- <link href="{{ asset('css/custom.css') }}" rel="stylesheet" /> --}}
    @yield('stylesheet')

    @stack('stylesheets')

     <!-- GOOGLE FONTS-->
   <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css' />
     <!-- TABLE STYLES-->

</head>


  <body>

    <header>
      <!-- Fixed navbar -->
      <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="#">{{ config('app.name') }}</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{{ route('professeur.index') }}">Acceuil<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Mon profil</a>
            </li>
          </ul>
          <div class="form-inline mt-2 mt-md-0">
             <a href="{{ route('logout') }}" onclick="event.preventDefault();document.getElementById('logout-form').submit();" class="btn btn-danger square-btn-adjust">Déconnexion</a>
            <form id="logout-form" action="{{ route('professeur.logout') }}" method="POST" style="display: none;">
                @csrf
            </form>
          </div>
        </div>
      </nav>
    </header>

    <!-- Begin page content -->
    <main role="main" class="container">
      <div class="starter-template">
        @yield('content')
      </div>
    </main>
    


    <footer class="footer">
      @include('layouts.partials._footer')
    
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

    <!-- SCRIPTS -AT THE BOTOM TO REDUCE THE LOAD TIME-->
    <!-- JQUERY SCRIPTS -->
    <script src={{ asset('backend/assets/libs/jquery/dist/jquery.min.js') }}></script>

      <!-- BOOTSTRAP SCRIPTS -->
    <script src={{ asset('backend/assets/libs/bootstrap/dist/js/bootstrap.min.js') }}></script>
    <script src={{ asset('bootstrap/js/bootstrap.bundle.min.js') }}></script>


    <!-- METISMENU SCRIPTS -->

    @stack('scripts')



    <script type="text/javascript">
        $(function () {
                      $('[data-toggle="popover"]').popover()
                    })
    </script>
    
       {{-- PACKAGES --}}
    <!--Flashy -->
    @include('flashy::message')
</body>

<!-- Mirrored from getbootstrap.com/docs/4.1/examples/sticky-footer-navbar/ by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 07 Nov 2018 23:41:57 GMT -->
</html>

resources/views/layouts/master.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}" dir="ltr">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="Bil Wifi" content="{{ config('app.name') }} by KinDev">
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href={{ asset('favicon.ico') }}>
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ !empty ($title) ? $title .' | '. config('app.name') : config('app.name') }}  </title>
	<!-- BOOTSTRAP STYLES-->
    <link href="{{ asset('bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
    {{-- <link href="{{ asset('css/bootstrap.css') }}" rel="stylesheet"> --}}
    @yield('stylesheet1')
     <!-- FONTAWESOME STYLES-->
        <!-- Custom CSS -->
    <link href="{{ asset('bootstrap/icons/font-awesome/css/fontawesome-all.css') }}" rel="stylesheet">
     <!-- MORRIS CHART STYLES-->
    
        <!-- CUSTOM STYLES-->
    <link href="{{ asset('css/custom.css') }}" rel="stylesheet" />
    @yield('stylesheet')

    @stack('stylesheets')

     <!-- GOOGLE FONTS-->
   <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css' />
     <!-- TABLE STYLES-->

    <!-- Date et heure -->
    <script type="text/javascript" src="{{ asset('js/date-heure.js') }}"></script>

</head>
<body>
    <div id="wrapper">
        <nav class="navbar navbar-default navbar-cls-top " role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">

         {{--        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button> --}}


         {{--        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button> --}}
                <a class="navbar-brand mx-auto d-block" href="{{ route('home') }}">TCotes | ISPT </a> 
            </div>
            <div style="color: white; padding: 15px 50px 5px 50px; float: right; font-size: 16px;">
            <h2 class="badge badge-info">Section</h2>   
            <span id="date_heure"></span> &nbsp; 
            <a href="{{ route('logout') }}" onclick="event.preventDefault();document.getElementById('logout-form').submit();" class="btn btn-danger square-btn-adjust">Déconnexion</a>
            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                @csrf
            </form>
            </div>
        </nav>   
           <!-- /. NAV TOP  -->
        <nav class="navbar-default navbar-side sidebar-nav" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav " id="main-menu">
    				<li class="text-center mx-auto d-block sidebar-item">
                        <img style="max-width: 60%" src="{{ asset('/img/logoIspt.gif') }}" class="user-image img-responsive img-fluid"/>
    				</li>
                    <li>
                        <a class="sidebar-link has-arrow waves-effect waves-dark"  href="{{ route('home') }}"><i class="fas fa-tachometer-alt fa-2x"></i> Tableau de bord</a>
                    </li>
                    {{-- <li>
                        <a class="sidebar-link has-arrow waves-effect waves-dark"  href="#"><i class=" fas fa-th-list fa-2x"></i>Gestion des étudiants</a>
                    </li>
                    <li>
                        <a class="sidebar-link has-arrow waves-effect waves-dark"  href="#"><i class=" fas fa-th-list fa-2x"></i>Gestion des professeurs</a>
                    </li>
                    <li>
                        <a class="sidebar-link has-arrow waves-effect waves-dark"  href="{{ route('section.index') }}"><i class=" fas fa-th-list fa-2x"></i>Gestion des cours</a>
                    </li> --}}
                    {{-- <li>
                        <a class="sidebar-link has-arrow waves-effect waves-dark"  href="#"><i class=" fas fa-th-list fa-2x"></i>Gestion des cours</a>
                    </li> --}}
                    <li>
                        <a class="sidebar-link has-arrow waves-effect waves-dark"  href="#"><i class=" fas fa-user fa-2x"></i> Mon profil</a>
                    </li>
                   
				{{-- 	<!-- Multi link -->
                    <li>
                        <a href="#"><i class="fa fa-sitemap fa-2x"></i> Enrôlements<span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a href="#">Enrôler étudiant</a>
                            </li>
                            <li>
                                <a href="#">Liste des enrôlés</a>
                            </li>
                            <li>
                                <a href="#">Second Level Link<span class="fa arrow"></span></a>
                                <ul class="nav nav-third-level">
                                    <li>
                                        <a href="#">Third Level Link</a>
                                    </li>
                                    <li>
                                        <a href="#">Third Level Link</a>
                                    </li>
                                    <li>
                                        <a href="#">Third Level Link</a>
                                    </li>

                                </ul>
                               
                            </li>
                        </ul>
                    </li>  --}} 
                </ul>
               
            </div>
            
        </nav>  
        <!-- /. NAV SIDE  -->
        <div id="page-wrapper" >
          
                     {{-- <a href=""><i class="fas fa-arrow-circle-left fa-2x"></i></a>    --}}

            <div id="page-inner" style="background-color: : #F3F3F3">
               {{--  <div class="row">
                    <div class="col-md-12">
                     <h2 class="btn btn-success">{{ \App\Http\Controllers\Helper::getUserRole() }}</h2>   
                        <h5>home Jhon Deo , Love to see you back. </h5>
                    </div>
                </div> --}}
                 {{-- <hr /> --}}
                @yield('content')
                 <!-- /. ROW  -->
            </div>
               
            @include('layouts.partials._footer')
        </div>
             <!-- /. PAGE INNER  -->

    </div>
         <!-- /. PAGE WRAPPER  -->
     <!-- /. WRAPPER  -->

    <!-- SCRIPTS -AT THE BOTOM TO REDUCE THE LOAD TIME-->
    <!-- JQUERY SCRIPTS -->
    <script src={{ asset('backend/assets/libs/jquery/dist/jquery.min.js') }}></script>

      <!-- BOOTSTRAP SCRIPTS -->
    <script src={{ asset('backend/assets/libs/bootstrap/dist/js/bootstrap.min.js') }}></script>
    <script src={{ asset('bootstrap/js/bootstrap.bundle.min.js') }}></script>


    <!-- METISMENU SCRIPTS -->
    <script src="{{ asset("js/jquery.metisMenu.js") }}"></script>

    @stack('scripts')


         <!-- CUSTOM SCRIPTS -->
    <script src="{{ asset("js/custom.js") }}"></script>
    <script src="{{ asset("js/raphael-2.1.0.min.js") }}"></script>
    <script src="{{ asset("js/morris.js") }}"></script>
    <script type="text/javascript">window.onload = date_heure('date_heure');</script>


    <script type="text/javascript">
        $(function () {
                      $('[data-toggle="popover"]').popover()
                    })
    </script>
    
       {{-- PACKAGES --}}
    <!--Flashy -->
    @include('flashy::message')
</body>
</html>